### ISSUE TITLE
Bad case in {{?rfc}} reference causes inconsistent result

### ISSUE THREAD

**Issue by fenner** [cabo/kramdown-rfc2629#14]
I accidentally wrote `{{?rfc4293}}`, and the resulting XML was:

```
<xref target="rfc4293"/>
```

but of course the id of the (wonderfully auto-)downloaded reference was

```
<reference anchor='RFC4293'>
```

so xml2rfc gripes:

```
ERROR: Unable to validate the XML document: draft.xml
 draft.xml: Line 59: IDREF attribute target references an unknown ID "rfc4293"
```

I don't know whether the right fix is to DWIM by making the xref refer to the uppercase value, or return an error while running kramdown-rfc2629.

**Comment by cabo** [comment]
This is magically fixed by the new reference anchor selection code in 1.1: The fact that you wrote the reference anchor in lower case also causes that to override the one in the bibxml file.  There is still no very good error message if you choose `stand_alone: no`, but I think I'll just let slide that one for now; people who use that will just have to examine the generated XML.

Sorry for the 21-month RTT on this one...
