### ISSUE TITLE
RFC references with annotations

### ISSUE THREAD

**Issue by reschke** [cabo/kramdown-rfc2629#42]
I'd like to replicate what we have in https://greenbytes.de/tech/webdav/rfc6265.html#RFC3490

I currently have:

~~~
  RFC3490:
    title: "Internationalizing Domain Names in Applications (IDNA)"
    seriesinfo:
      RFC: 3490
    date: 2003-03
    author:
      -
        ins: P. Faltstrom
        ins: P. Hoffman
        ins: A. Costello
    ann: See {{idna-migration}} for an explanation why the normative reference to an obsoleted specification is needed.
~~~

Problems:

1. Does seem to ignore the contents, message is: "*** redundant in RFC3490: {"title"=>"Internationalizing Domain Names in Applications (IDNA)", "seriesinfo"=>{"RFC"=>3490}, "date"=>"2003-03", "author"=>[{"ins"=>"A. Costello"}], "ann"=>"See {{idna-migration}} for an explanation why the normative reference to an obsoleted specification is needed."}"
2. Even if I rename the target, it doesn't expand the section reference in the annotation.

**Comment by cabo** [comment]
Indeed, the current mechanism either can import a reference from bibxml or can have one in the YAML.  The detection that bibxml should be consulted is based on the name of the reference.  That's why kramdown-rfc alerts you that the YAML is ignored.

As you seem to have noticed, the fix is to rename the anchor name from something that triggers the bibxml import.

Should there be code to mix and match bibxml references with items taken from the YAML?  That is likely to be messy (but could be based on RFC7396 merge patch semantics).


Your observation 2 is a different bug: There is no markdown processing of the fields in the reference.  Hmm.  I don't have a good handle on which fields should be markdown processed.  Clearly, we could do this with ann(otation).  What else?  Some weirdness would remain, as this is not exactly identical to a <t> element, and the processing will be separate from that of the main document.

**Comment by reschke** [comment]
1. I think it would be sufficient if the presence of local YAML always disables the automatic import (but maybe you'd need to make that optional for backwards compat).

2. I think for now it only applies to ann(otation); after all, the matching XML element is defined that way (https://greenbytes.de/tech/webdav/rfc7749.html#element.annotation)

**Comment by cabo** [comment]
1.2.1 now allows you to override the bibxml from YAML.
Suppress the warning by adding "override: yes" to the YAML entry.
(A warning is definitely indicated -- e.g., your example is missing the DOI.)

**Comment by reschke** [comment]
My tooling (XSLTs) automatically inserts DOIs for RFCs (this is IMHO far superior to having to embed them and potentially getting them wrong)

**Comment by cabo** [comment]
Well, the RFC editor will fix that for you in the XML :-)

1.2.2 now markdown-processes annotations.  Please report any weirdness.

**Comment by reschke** [comment]
What gets submitted to the RFC-Editor is the output of clean-for-DTD.xslt, and that has the DOIs inserted...

**Comment by reschke** [comment]
Works great, thanks!
